steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: "bash"
  args: [
    '-c',
    'gcloud secrets versions access $_SECRET_VERSION --secret=${_SERVICE_NAME} > .env'
  ]
- name: node
  entrypoint: npm
  args: ['install']
- name: node
  entrypoint: npm
  args: ['test']
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$BRANCH_NAME-$SHORT_SHA', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$BRANCH_NAME-$SHORT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: [
    'beta',
    'run',
    'jobs',
    'create',
    '${_SERVICE_NAME}',
    '--image',
    'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$BRANCH_NAME-$SHORT_SHA',
    '--tasks',
    '3',
    '--set-env-vars',
    'SLEEP_MS=10000',
    '--set-env-vars',
    'FAIL_RATE=0.5',
    '--max-retries',
    '5',
    '--region',
    '$_REGION'
  ]
images:
- gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$BRANCH_NAME-$SHORT_SHA
options:
  logging: CLOUD_LOGGING_ONLY